import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SmoothScroll from "@/Component/lenis-smooth-scroll";
import { Toaster } from "@/components/ui/sonner";



export const metadata: Metadata = {
  title: "BuchiLondon Enterprises",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SmoothScroll>
          {children}
          <Toaster richColors />
        </SmoothScroll>
      </body>
    </html>
  );
}
